# Generated by Django 4.1.7 on 2023-03-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_carmark_carmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_to',
        ),
    ]
