# Generated by Django 4.1.7 on 2023-03-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_remove_carmodel_year_from_remove_carmodel_year_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='model_class',
            field=models.CharField(max_length=20, null=True, verbose_name='Класс авто'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_from',
            field=models.IntegerField(null=True, verbose_name='Год начала производства'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_to',
            field=models.IntegerField(null=True, verbose_name='Год окончания производства'),
        ),
    ]
