# Generated by Django 4.1.7 on 2023-03-07 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_carmodel_model_class_carmodel_year_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=150, null=True, verbose_name='Наименование')),
                ('max_age', models.IntegerField(null=True, verbose_name='Год окончания производства')),
                ('additional_requirements', models.TextField(null=True, verbose_name='Дополнительные требования')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmark')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel')),
                ('status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='default.requeststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
