# Generated by Django 4.1.7 on 2023-03-08 00:13

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_alter_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'verbose_name': 'Статус запроса', 'verbose_name_plural': 'Статусы запроса'},
        ),
        migrations.AlterField(
            model_name='request',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_mark', chained_model_field='car_mark', on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel'),
        ),
        migrations.AlterField(
            model_name='request',
            name='color',
            field=models.CharField(max_length=150, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='request',
            name='max_age',
            field=models.IntegerField(null=True, verbose_name='Год выпуска от'),
        ),
    ]
