# Generated by Django 4.1.7 on 2023-03-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_remove_request_timestamp_request_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='max_age',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Год выпуска от'),
        ),
    ]
