# Generated by Django 4.1.7 on 2023-03-08 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_alter_request_max_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска от'),
        ),
    ]
