# Generated by Django 4.1.7 on 2023-03-08 03:22

import default.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_alter_request_max_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус предложения',
                'verbose_name_plural': 'Статусы предложения',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='body_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Седан'), (2, 'Хэтчбэк'), (3, 'Родстер'), (4, 'Лифтбэк'), (5, 'Универсал'), (6, 'Купе'), (7, 'Кроссовер'), (8, 'Внедорожник'), (9, 'Пикап'), (10, 'Микро'), (11, 'Лимузин'), (12, 'Фургон/Минивэн'), (13, 'Другой')], null=True, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='request',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='request',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)'),
        ),
        migrations.AddField(
            model_name='request',
            name='fuel',
            field=models.IntegerField(blank=True, choices=[(1, 'Бензин'), (2, 'Дизель'), (3, 'Электромотор'), (4, 'Гибрид')], null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='request',
            name='max_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег до (км)'),
        ),
        migrations.AddField(
            model_name='request',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Бюджет до (RUB)'),
        ),
        migrations.AddField(
            model_name='request',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Бюджет от (RUB)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска от'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=150, verbose_name='Цвет')),
                ('year_of_issue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска')),
                ('body_type', models.IntegerField(blank=True, choices=[(1, 'Седан'), (2, 'Хэтчбэк'), (3, 'Родстер'), (4, 'Лифтбэк'), (5, 'Универсал'), (6, 'Купе'), (7, 'Кроссовер'), (8, 'Внедорожник'), (9, 'Пикап'), (10, 'Микро'), (11, 'Лимузин'), (12, 'Фургон/Минивэн'), (13, 'Другой')], null=True, verbose_name='Тип кузова')),
                ('fuel', models.IntegerField(blank=True, choices=[(1, 'Бензин'), (2, 'Дизель'), (3, 'Электромотор'), (4, 'Гибрид')], null=True, verbose_name='Топливо')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объем двигателя')),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена (RUB)')),
                ('location', models.CharField(max_length=400, verbose_name='Адрес местонахождения авто')),
                ('additional_properties', models.TextField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('last_update', default.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmark')),
                ('car_model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_mark', chained_model_field='car_mark', on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='default.offerstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
