# Generated by Django 4.1.7 on 2023-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0013_user_full_name_user_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Поставщик'), (2, 'Покупатель')], null=True, verbose_name='Тип пользователя'),
        ),
    ]
