# Generated by Django 4.1.7 on 2023-03-11 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0014_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_mark', chained_model_field='car_mark', on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.TextField(verbose_name='Адрес местонахождения авто'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='request',
            name='car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='request',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_mark', chained_model_field='car_mark', on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Test')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmark', verbose_name='Марка')),
                ('car_model', smart_selects.db_fields.GroupedForeignKey(group_field='car_mark', on_delete=django.db.models.deletion.CASCADE, to='default.carmodel')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
