# Generated by Django 4.1.7 on 2023-03-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_alter_offer_car_mark_alter_offer_car_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
