# Generated by Django 4.0.10 on 2023-03-14 22:06

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0017_alter_offer_status_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_mark', chained_model_field='car_mark', on_delete=django.db.models.deletion.DO_NOTHING, to='default.carmodel', verbose_name='Модель', view_name='chained_filter'),
        ),
    ]
